# Generated by Django 3.2.3 on 2021-09-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extract',
            name='type',
            field=models.CharField(choices=[('redeem', 'redeem'), ('reload', 'reload'), ('cancelation', 'cancelation'), ('activation', 'activation')], max_length=12),
        ),
    ]
